(function () {
  const baseContent = {
    content: '',
    cover: null,
    status: 'demo',
    isPinned: false,
    isFeatured: false,
    createdAt: '日期待接入',
    updatedAt: '日期待接入',
    publishedAt: '日期待接入',
    readingTime: '-- 分钟',
    wordCount: '--',
    sourceUrl: null,
    placeholder: true,
  };

  window.KnowledgeMockData = {
    placeholder: true,
    author: {
      name: 'Lee Ethan',
      description: '作者简介待正式补充。',
      avatar: null,
      placeholder: true,
    },
    contentTypes: [
      { id: 'article', label: '技术文章' },
      { id: 'solution', label: '算法题解' },
      { id: 'note', label: '学习笔记' },
      { id: 'project', label: '项目记录' },
      { id: 'essay', label: '思考随笔' },
    ],
    posts: [
      Object.assign({}, baseContent, {
        id: 'demo-article-1',
        slug: 'demo-technical-article',
        type: 'article',
        title: '演示内容：技术文章标题',
        summary: '用于展示普通技术文章的信息结构、摘要排版和元数据区域。',
        category: '技术文章',
        tags: ['C++', '开发记录'],
        isPinned: true,
        isFeatured: true,
      }),
      Object.assign({}, baseContent, {
        id: 'demo-article-2',
        slug: 'demo-tutorial-article',
        type: 'article',
        title: '演示内容：教程文章标题',
        summary: '该对象仅用于前端框架验证，不代表作者已经正式发布。',
        category: '技术文章',
        tags: ['Web 开发', '教程'],
      }),
      Object.assign({}, baseContent, {
        id: 'demo-solution-1',
        slug: 'demo-solution-binary-search',
        type: 'solution',
        title: '演示题解：算法问题 A',
        summary: '展示题解专用元数据、算法标签和复杂度信息。',
        category: '算法题解',
        tags: ['二分', '数据结构'],
        isFeatured: true,
        solution: {
          platform: '平台占位',
          problemId: '题号待接入',
          problemTitle: '题目名称占位 A',
          problemUrl: null,
          difficulty: '难度待接入',
          algorithms: ['算法标签', '待接入'],
          language: 'C++',
          timeComplexity: '待分析',
          spaceComplexity: '待分析',
          accepted: null,
        },
      }),
      Object.assign({}, baseContent, {
        id: 'demo-solution-2',
        slug: 'demo-solution-graph',
        type: 'solution',
        title: '演示题解：算法问题 B',
        summary: '用于验证不同题解在列表和详情页中的展示差异。',
        category: '算法题解',
        tags: ['图论', '搜索'],
        solution: {
          platform: '平台占位',
          problemId: '题号待接入',
          problemTitle: '题目名称占位 B',
          problemUrl: null,
          difficulty: '难度待接入',
          algorithms: ['图论', '搜索'],
          language: 'C++',
          timeComplexity: '待分析',
          spaceComplexity: '待分析',
          accepted: null,
        },
      }),
      Object.assign({}, baseContent, {
        id: 'demo-note-1',
        slug: 'demo-study-note',
        type: 'note',
        title: '演示内容：学习笔记标题',
        summary: '用于展示 408、数学或其他课程笔记的内容结构。',
        category: '408',
        tags: ['操作系统', '学习笔记'],
      }),
      Object.assign({}, baseContent, {
        id: 'demo-project-1',
        slug: 'demo-project-log',
        type: 'project',
        title: '演示内容：项目开发记录',
        summary: '用于展示项目目标、开发过程、阶段状态和技术标签。',
        category: '项目开发',
        tags: ['项目', 'Web 开发'],
      }),
    ],
    categories: [
      { id: 'technology', label: '技术文章', count: '--', placeholder: true },
      { id: 'solutions', label: '算法题解', count: '--', placeholder: true },
      { id: 'cs408', label: '408', count: '--', placeholder: true },
      { id: 'math', label: '数学', count: '--', placeholder: true },
      { id: 'projects', label: '项目开发', count: '--', placeholder: true },
      { id: 'game-dev', label: '游戏开发', count: '--', placeholder: true },
      { id: 'essays', label: '随笔', count: '--', placeholder: true },
    ],
    domains: ['C++', '数据结构', '算法', '操作系统', '计算机网络', '计算机组成原理', '线性代数', 'Unity', 'Web 开发'],
    platforms: [
      { label: 'GitHub', href: 'https://github.com/dfsjiv', placeholder: false },
      { label: 'Codeforces', href: null, placeholder: true },
      { label: '牛客', href: null, placeholder: true },
      { label: '洛谷', href: null, placeholder: true },
      { label: '其他文章平台', href: null, placeholder: true },
    ],
    topics: ['算法基础', '408 学习', '操作系统', '计算机网络', '项目开发'],
    tags: ['C++', '算法', '数据结构', '操作系统', '计算机网络', '408', '数学', 'Web 开发', 'Unity', '随笔'],
    archives: [
      { year: '年份待接入', month: '月份待接入', count: '--', placeholder: true },
      { year: '年份待接入', month: '月份待接入', count: '--', placeholder: true },
    ],
    updates: [
      { time: '时间待接入', type: '文章更新', text: '旧文章修改记录占位。', placeholder: true },
      { time: '时间待接入', type: '题解补充', text: '算法题解补充记录占位。', placeholder: true },
      { time: '时间待接入', type: '项目进度', text: '项目开发进度记录占位。', placeholder: true },
    ],
    stats: [
      { label: '文章数量', value: '--' },
      { label: '题解数量', value: '--' },
      { label: '分类数量', value: '--' },
      { label: '标签数量', value: '--' },
      { label: '总字数', value: '--' },
      { label: '最后更新', value: '--' },
    ],
  };
}());
